name: Build npm package

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21d

      - name: Build package
        env:
          ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: >-
          env
          ls -lah /opt/hostedtoolcache/Java_Zulu_jdk/11.0.20-8/x64 /usr/lib/jvm/temurin-8-jdk-amd64 /opt/hostedtoolcache/ndk/r21d/x64 /usr/local/lib/android/sdk/ndk/25.2.9519653 /usr/lib/jvm/temurin-17-jdk-amd64 /usr/local/lib/android/sdk/ndk/25.2.9519653 /usr/local/lib/android/sdk
          exit 2

      - run: echo "PACKAGE_NAME=$(ls -l | egrep -o "react-native-reanimated-(.*)(=?\.tgz)")" >> $GITHUB_ENV
      
      - name: Upload npm package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: '*.tgz'

      - name: Compress Android build output
        if: ${{ inputs.upload_binaries }}
        run: zip -r android-build-output.zip build_output

      - name: Upload Android build folder
        if: ${{ inputs.upload_binaries }}
        uses: actions/upload-artifact@v3
        with:
          name: android-build-output
          path: android-build-output.zip
          retention-days: 5
